### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sambitsargam**
I UPDATED SOME MINOR MISTAKES THAT MY EYE COUGHT .......
YOU CAN MERGE IT

### CODE REVIEW

**Comment by scientific-dev** [comment]
Now i am sure that you are an english teacher. Just kidding but thanks for helping
This repo was actually gonna be archived for low quality of codes

But i will try to remake this repo again with good codes. Try to contribute codes rather than README updates and thanks for it

**Comment by scientific-dev** [comment]
Secondly sorry i just now viewed and found a lot of mess in codes coz see `print()` is in python but you made it capital to `Print()` which made mess but ok i will fix it later

**Comment by sambitsargam** [comment]
Thanks for merging bro.......
are you indian

**Comment by scientific-dev** [comment]
Yes but still a student

**Comment by sambitsargam** [comment]
sorry for that ........ i was  distracted and enjoying tv so that mistake
made by me

**Pull request merged**
